// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojnosetdjpkarzttonvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbm9zZXRkanBrYXJ6dHRvbnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzM0ODksImV4cCI6MjA1NTA0OTQ4OX0.vJRxT72gt9e4WH7AjwKFZ9u3AodFosJnGbYS3RLchUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);